server:
  port: 8080
#  servlet:
#    contextPath: /SpringBootKubernetes
---
spring:
  application:
    name: user-jwt-service
  profiles: local, default
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:~/users
    username: root
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
      maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka      
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/websystique
    username: myuser
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect    